# Generated by Django 3.1.6 on 2021-04-05 20:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_auto_20210327_2014'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='popular',
            new_name='featured',
        ),
    ]
