# Generated by Django 3.1.6 on 2021-04-07 11:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0010_product_avg_rating'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='avg_rating',
            new_name='avgRating',
        ),
    ]
